### ISSUE TITLE
Issue in Live 11 suite. 

### ISSUE THREAD

**Issue by DtwaTechno** [mganss/DrumGen#2]
I encountered this issue when grouping Drumbrain with a few other max4live devices.  The intent was to have a central hub to quickly create patterns in a live performance environment. 

After creating simple device macros for an on/off toggle and assigning midi to a controller for each parameter in Drumbrain, I noticed that I had lost the ability to generate clips.

I am not sure if this is a known issue or not.  However I wanted to submit it, just in case. 

Also, is there a way to midi assign the preset bank?  If not, that would be a great feature. 

Lastly, a cue parameter for each instrument would be the bees knees for this device. Instead of bouncing it out, being able to select each instrument and preview it via headphones would be the greatest thing, like ever.  Being able to mute the tracks is good, but cueing them would be soooo sweet.  An additional button would be all you need, per instrument, and perhaps a master cue volume parameter to pair with it. 

This device is awesome as is.  The above would make it awesome- er.  Haha.

**Comment by mganss** [comment]
This seems to occur whenever the device is grouped. Will look into it.

MIDI mapping the presets is not possible. I'll add a MIDI mappable control to recall a preset by number (like in Aicd).

Do you know an M4L device that has a cue feature?

**Comment by mganss** [comment]
I've fixed the grouping bug in 1.3.0 and have also added a MIDI mappable preset recall (open the preset panel and it's at the bottom).

I'm closing this for now but feel free to open a separate issue re the cue feature or just add more comments here.

**Comment by DtwaTechno** [comment]
Touche, I do not. That is a great point.

I really appreciate this. The mapping will make a big difference.  Your
device is the best Drum pattern generator I've encountered so far for those
with an analog persective.  Generating a basis for patterns on the fly has
really sped up live performance options.

Gratitude.
